---
title: "Correlation Tables for Time and Thoughts"
author: "Irene Xu"
date: "Last updated: `r Sys.Date()`"
output:
  html_document:
    theme: yeti
    code_folding: hide
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: true
      smooth_scroll: true
---
<br/>

**Study: Suicide Trajectory**    

The goal of this file is to create a table that summaries the correlations between time and thoughts.

<br/>
<br/>
```{r setup, include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gtsummary)
library(gt)
library(modelsummary)
source("helper_functions/apa_table_formatter.R")
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
alldata <- read_csv("../data/psai_processed_100421.csv")
```

# Select variables for the table
```{r}
tt <- alldata %>%
  select(think_bin, mull_bin, dec_bin, firstmethod_bin, suremethod_bin, firstplace_bin, sureplace_bin,
         thoughts_amt, thoughts_want, thoughts_not_want, thoughts_net, 
         prep_total)
```

```{r}
tt <- tt %>%
  select("1. SI Onset" = think_bin,
         "2. Start to Mull" = mull_bin,
         "3. Decide to Attempt" = dec_bin,
         "4. Start to Consider Method" = firstmethod_bin,
         "5. Decide on Method" = suremethod_bin,
         "6. Start to Consider Place" = firstplace_bin,
         "7. Decide on Place" = sureplace_bin,
         "8. Thoughts Towards Attempt" = thoughts_want,
         "9. Thoughts Against Attempt" = thoughts_not_want,
         "10. All Thoughts" = thoughts_amt,
         "11. Counterbalanced Thoughts" = thoughts_net,
         "12. Preparatory Actions" = prep_total)
```

```{r}
cor <- datasummary_correlation(tt, output = "gt", align = "lllllllllllll") 
cor <- cor %>% 
  cols_width(everything() ~ px(60)) %>%
  tab_options(table.font.size = 14) %>%
  cols_width("1. SI Onset" ~ px(50),
         "2. Start to Mull" ~ px(50),
         "3. Decide to Attempt" ~ px(50),
         "4. Start to Consider Method" ~ px(50),
         "5. Decide on Method" ~ px(50),
         "6. Start to Consider Place" ~ px(50),
         "7. Decide on Place" ~ px(50),
         "8. Thoughts Towards Attempt" ~ px(50),
         "9. Thoughts Against Attempt" ~ px(50),
         "10. All Thoughts" ~ px(50),
         "11. Counterbalanced Thoughts" ~ px(50),
         "12. Preparatory Actions" ~ px(50),
         everything() ~ px(190)) %>%
  cols_label("1. SI Onset" = "1",
         "2. Start to Mull" = "2",
         "3. Decide to Attempt" = "3",
         "4. Start to Consider Method" = "4",
         "5. Decide on Method" = "5",
         "6. Start to Consider Place" = "6",
         "7. Decide on Place" = "7",
         "8. Thoughts Towards Attempt" = "8",
         "9. Thoughts Against Attempt" = "9",
         "10. All Thoughts" = "10",
         "11. Counterbalanced Thoughts" = "11",
         "12. Preparatory Actions" = "12") %>%
  apa_cor_formatter("", 85)
gtsave(cor, "cor_matrix.png", "../tables/")
```

