---
title: "Preparatory Actions Figures"
author: "Irene Xu"
date: "Last updated: `r Sys.Date()`"
output:
  html_document:
    theme: yeti
    code_folding: hide
---
<br/>

**Study: Suicide Trajectory**    

The goal of this file is to create figures that visualize the distribution of the 4 thought variables.

<br/>
<br/>
```{r setup, include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gridExtra)
library(papaja)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
alldata <- read_csv("../data/psai_processed_100421.csv") %>%
  filter(!subject %in% c(1, 55)) %>%
  mutate(group = ifelse(group == "Aborted/Interrupted Attempters", "ab", "at"))
```

# 1. Select variables  
```{r}
prep <- alldata %>%
  select(group, prep_total)
```

# 2. Plot the distribution of preparatory actions
```{r prep-plot, fig.width=6, fig.height=4}
p1 <- ggplot(prep, aes(x = prep_total,  fill = group)) +
  geom_histogram(stat="count", 
                 position = position_dodge2(preserve = "single", padding = 0.1)) +
  theme_apa()+
  scale_fill_manual(name = "Type of the Most Recent Attempt",
                    labels = c("Aborted", "Actual"),
                    values = c("skyblue4", "darkgoldenrod2")) +
  labs(x = "Number of Preparatory Actions", y = "Number of Participants") +
  scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)) +
  scale_y_continuous(expand = c(0.008, 0)) +
  theme(legend.position = c(0.75, 0.82)) 
grid.arrange(p1)
ggsave("../figures/prep_plot_apa.png", p1)
```


